# Generated by Django 5.2.17 on 2026-10-04 11:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_reminders', models.BooleanField(default=True)),
                ('workout_reminder', models.BooleanField(default=True)),
                ('workout_lead_minutes', models.PositiveSmallIntegerField(default=10)),
                ('wake_up', models.BooleanField(default=True)),
                ('tasks', models.BooleanField(default=True)),
                ('tasks_time', models.TimeField(default=datetime.time(18, 0))),
                ('habits', models.BooleanField(default=True)),
                ('habits_time', models.TimeField(default=datetime.time(20, 0))),
                ('night_review', models.BooleanField(default=True)),
                ('night_review_time', models.TimeField(default=datetime.time(22, 0))),
                ('goal_deadlines', models.BooleanField(default=True)),
                ('goal_deadlines_time', models.TimeField(default=datetime.time(9, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sent_at'], name='notificatio_sent_at_188b25_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_reminder_per_key')],
            },
        ),
    ]
