# Generated by Django 5.2.17 on 2026-10-04 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('morning', 'Morning'), ('workout', 'Workout'), ('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('meal', 'Meal'), ('rest', 'Rest'), ('growth', 'Growth'), ('night', 'Night')], default='personal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reminder_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Remind this many minutes before the start. Empty = no reminder.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('repeat', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays (Mon–Fri)'), ('weekends', 'Weekends (Sat–Sun)'), ('selected_days', 'Selected days'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('morning', 'Morning'), ('workout', 'Workout'), ('work', 'Work'), ('study', 'Study'), ('personal', 'Personal'), ('meal', 'Meal'), ('rest', 'Rest'), ('growth', 'Growth'), ('night', 'Night')], default='personal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reminder_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Remind this many minutes before the start. Empty = no reminder.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('occurrence_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='upcoming', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_customized', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='planner.scheduletemplate')),
            ],
            options={
                'ordering': ['date', 'start_time', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduletemplate',
            index=models.Index(fields=['user', 'is_active'], name='planner_sch_user_id_f06330_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleitem',
            index=models.Index(fields=['user', 'date'], name='planner_sch_user_id_a3cf4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('template', 'occurrence_date'), name='unique_occurrence_per_template_day'),
        ),
    ]
