# Generated by Django 5.2.17 on 2026-10-06 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_routine_routineitem_routinelog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='kind',
            field=models.CharField(choices=[('morning', 'Morning routine'), ('minimum', 'Minimum day')], default='morning', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'minimum')), fields=('user',), name='one_minimum_checklist_per_user'),
        ),
        migrations.AddField(
            model_name='minimumday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimum_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='minimumday',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='one_minimum_day_per_user_per_day'),
        ),
    ]
