# Generated by Django 5.2.17 on 2026-10-04 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WakeChallengeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('challenge_type', models.CharField(choices=[('dance', 'Dance'), ('jumping_jacks', 'Jumping jacks'), ('squats', 'Squats'), ('math', 'Math')], max_length=20)),
                ('method', models.CharField(choices=[('camera', 'Camera (movement detected)'), ('manual', 'Timer (no camera)'), ('math', 'Math answers')], max_length=10)),
                ('target_seconds', models.PositiveSmallIntegerField(default=60)),
                ('active_seconds', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=12)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wake_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'date', 'status'], name='challenges__user_id_6b4589_idx')],
            },
        ),
    ]
