# Generated by Django 5.2.17 on 2026-10-04 10:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('study', 'Study'), ('career', 'Career'), ('money', 'Money'), ('reading', 'Reading'), ('coding', 'Coding'), ('projects', 'Personal projects'), ('mindset', 'Mindset'), ('relationships', 'Relationships'), ('other', 'Other')], default='other', max_length=20)),
                ('measure', models.CharField(choices=[('boolean', 'Done / not done'), ('number', 'Number'), ('currency', 'Money'), ('duration', 'Time (hours)'), ('count', 'Count'), ('percentage', 'Percentage')], default='number', max_length=12)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_main', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_main', 'deadline', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_goal_user_id_7ad9fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('user',), name='one_main_goal_per_user'),
        ),
        migrations.AddIndex(
            model_name='goalprogress',
            index=models.Index(fields=['user', 'date'], name='goals_goalp_user_id_449eb5_idx'),
        ),
    ]
