# Generated by Django 5.2.17 on 2026-10-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='plan_rows', to='workouts.exercise'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='session_rows', to='workouts.exercise'),
        ),
    ]
