# Generated by Django 5.2.17 on 2026-10-04 10:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersettings_weekly_workout_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='daily_target_score',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='score_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='streak_threshold',
            field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='wake_grace_minutes',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='wake_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
