# Generated by Django 5.2.17 on 2026-10-04 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersettings_daily_target_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='wake_challenge_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='wake_challenge_seconds',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='wake_challenge_type',
            field=models.CharField(choices=[('dance', 'Dance'), ('jumping_jacks', 'Jumping jacks'), ('squats', 'Squats'), ('math', 'Math')], default='dance', max_length=20),
        ),
    ]
