# Generated by Django 5.2.17 on 2026-10-06 01:56

from django.db import migrations, models


def existing_accounts_are_already_set_up(apps, schema_editor):
    """
    Everyone who has an account when this ships already uses the app, so they never
    see the setup wizard. Accounts without a settings row yet get one, marked done.
    New sign-ups after this keep the default (False) and see the wizard once.
    """
    User = apps.get_model("users", "User")
    UserSettings = apps.get_model("users", "UserSettings")
    UserSettings.objects.update(onboarding_completed=True)
    missing = User.objects.filter(settings__isnull=True)
    UserSettings.objects.bulk_create([UserSettings(user=user, onboarding_completed=True) for user in missing])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersettings_wake_challenge_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        # Reversing only drops the column, so there's nothing to undo here.
        migrations.RunPython(existing_accounts_are_already_set_up, migrations.RunPython.noop),
    ]
